// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/grpc/facilities.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FacilitiesServiceClient is the client API for FacilitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FacilitiesServiceClient interface {
	CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error)
	UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error)
}

type facilitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFacilitiesServiceClient(cc grpc.ClientConnInterface) FacilitiesServiceClient {
	return &facilitiesServiceClient{cc}
}

func (c *facilitiesServiceClient) CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error) {
	out := new(CreateFacilityResponse)
	err := c.cc.Invoke(ctx, "/grpc.FacilitiesService/CreateFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilitiesServiceClient) UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error) {
	out := new(CreateFacilityResponse)
	err := c.cc.Invoke(ctx, "/grpc.FacilitiesService/UpdateFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilitiesServiceServer is the server API for FacilitiesService service.
// All implementations should embed UnimplementedFacilitiesServiceServer
// for forward compatibility
type FacilitiesServiceServer interface {
	CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error)
	UpdateFacility(context.Context, *UpdateFacilityRequest) (*CreateFacilityResponse, error)
}

// UnimplementedFacilitiesServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFacilitiesServiceServer struct {
}

func (UnimplementedFacilitiesServiceServer) CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacility not implemented")
}
func (UnimplementedFacilitiesServiceServer) UpdateFacility(context.Context, *UpdateFacilityRequest) (*CreateFacilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFacility not implemented")
}

// UnsafeFacilitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacilitiesServiceServer will
// result in compilation errors.
type UnsafeFacilitiesServiceServer interface {
	mustEmbedUnimplementedFacilitiesServiceServer()
}

func RegisterFacilitiesServiceServer(s grpc.ServiceRegistrar, srv FacilitiesServiceServer) {
	s.RegisterService(&FacilitiesService_ServiceDesc, srv)
}

func _FacilitiesService_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServiceServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FacilitiesService/CreateFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServiceServer).CreateFacility(ctx, req.(*CreateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilitiesService_UpdateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilitiesServiceServer).UpdateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FacilitiesService/UpdateFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilitiesServiceServer).UpdateFacility(ctx, req.(*UpdateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FacilitiesService_ServiceDesc is the grpc.ServiceDesc for FacilitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FacilitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FacilitiesService",
	HandlerType: (*FacilitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacility",
			Handler:    _FacilitiesService_CreateFacility_Handler,
		},
		{
			MethodName: "UpdateFacility",
			Handler:    _FacilitiesService_UpdateFacility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/facilities.proto",
}
