// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/grpc/tank.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TankServiceClient is the client API for TankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TankServiceClient interface {
	CreateTank(ctx context.Context, in *CreateTankRequest, opts ...grpc.CallOption) (*CreateTankResponse, error)
	UpdateTank(ctx context.Context, in *UpdateTankRequest, opts ...grpc.CallOption) (*CreateTankResponse, error)
}

type tankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTankServiceClient(cc grpc.ClientConnInterface) TankServiceClient {
	return &tankServiceClient{cc}
}

func (c *tankServiceClient) CreateTank(ctx context.Context, in *CreateTankRequest, opts ...grpc.CallOption) (*CreateTankResponse, error) {
	out := new(CreateTankResponse)
	err := c.cc.Invoke(ctx, "/grpc.TankService/CreateTank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tankServiceClient) UpdateTank(ctx context.Context, in *UpdateTankRequest, opts ...grpc.CallOption) (*CreateTankResponse, error) {
	out := new(CreateTankResponse)
	err := c.cc.Invoke(ctx, "/grpc.TankService/UpdateTank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TankServiceServer is the server API for TankService service.
// All implementations should embed UnimplementedTankServiceServer
// for forward compatibility
type TankServiceServer interface {
	CreateTank(context.Context, *CreateTankRequest) (*CreateTankResponse, error)
	UpdateTank(context.Context, *UpdateTankRequest) (*CreateTankResponse, error)
}

// UnimplementedTankServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTankServiceServer struct {
}

func (UnimplementedTankServiceServer) CreateTank(context.Context, *CreateTankRequest) (*CreateTankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTank not implemented")
}
func (UnimplementedTankServiceServer) UpdateTank(context.Context, *UpdateTankRequest) (*CreateTankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTank not implemented")
}

// UnsafeTankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TankServiceServer will
// result in compilation errors.
type UnsafeTankServiceServer interface {
	mustEmbedUnimplementedTankServiceServer()
}

func RegisterTankServiceServer(s grpc.ServiceRegistrar, srv TankServiceServer) {
	s.RegisterService(&TankService_ServiceDesc, srv)
}

func _TankService_CreateTank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TankServiceServer).CreateTank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TankService/CreateTank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TankServiceServer).CreateTank(ctx, req.(*CreateTankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TankService_UpdateTank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TankServiceServer).UpdateTank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TankService/UpdateTank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TankServiceServer).UpdateTank(ctx, req.(*UpdateTankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TankService_ServiceDesc is the grpc.ServiceDesc for TankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TankService",
	HandlerType: (*TankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTank",
			Handler:    _TankService_CreateTank_Handler,
		},
		{
			MethodName: "UpdateTank",
			Handler:    _TankService_UpdateTank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/tank.proto",
}
